"""Canonical skills and role patterns used by the radar.

Matching is keyword-based: each skill has one or more aliases that are
compiled into word-boundary regexes in ``extract.py``. Role classification
uses the first matching pattern in ``ROLE_PATTERNS`` (more specific first).
"""

from __future__ import annotations

# Canonical skill name -> aliases (include the canonical form).
# Keep aliases specific enough to avoid obvious false positives.
SKILL_ALIASES: dict[str, tuple[str, ...]] = {
    "python": ("python", "python3"),
    "javascript": ("javascript", "java script"),
    "typescript": ("typescript",),
    "react": ("react.js", "reactjs", "react"),
    "vue": ("vue.js", "vuejs", "vue"),
    "angular": ("angular", "angularjs"),
    "next.js": ("next.js", "nextjs", "next js"),
    "svelte": ("svelte", "sveltekit"),
    "flutter": ("flutter",),
    "dart": ("dart",),
    "react native": ("react native", "react-native"),
    "node": ("node.js", "nodejs", "node"),
    "express": ("express.js", "expressjs", "express"),
    "nestjs": ("nestjs", "nest.js"),
    "sql": ("sql",),
    "postgres": ("postgresql", "postgres"),
    "mysql": ("mysql",),
    "mongodb": ("mongodb", "mongo db", "mongo"),
    "redis": ("redis",),
    "elasticsearch": ("elasticsearch", "elastic search", "opensearch"),
    "aws": ("aws", "amazon web services"),
    "azure": ("azure", "microsoft azure"),
    "gcp": ("gcp", "google cloud platform", "google cloud"),
    "docker": ("docker",),
    "kubernetes": ("kubernetes", "k8s"),
    "terraform": ("terraform",),
    "ansible": ("ansible",),
    "helm": ("helm",),
    "go": ("golang", "go lang", "go developer", "go engineer", "go programmer"),
    "rust": ("rust",),
    "java": ("java",),
    "kotlin": ("kotlin",),
    "swift": ("swift",),
    "php": ("php",),
    "ruby": ("ruby", "ruby on rails", "rails"),
    "c++": ("c++", "cplusplus", "cpp"),
    "c#": ("c#", "csharp", "c sharp"),
    ".net": (".net", "dotnet", "asp.net", "aspnet"),
    "django": ("django",),
    "flask": ("flask",),
    "fastapi": ("fastapi", "fast api"),
    "pandas": ("pandas",),
    "numpy": ("numpy",),
    "pytorch": ("pytorch", "py torch"),
    "tensorflow": ("tensorflow", "tensor flow"),
    "scikit-learn": ("scikit-learn", "sklearn", "scikit learn"),
    "llm": ("llms", "large language model", "large language models", "llm"),
    "rag": ("retrieval augmented", "retrieval-augmented", "rag"),
    "langchain": ("langchain", "lang chain"),
    "prompt engineering": ("prompt engineering", "prompt-engineering"),
    "openai": ("openai", "open ai"),
    "huggingface": ("hugging face", "huggingface"),
    "airflow": ("airflow", "apache airflow"),
    "spark": ("apache spark", "pyspark", "spark"),
    "kafka": ("kafka", "apache kafka"),
    "graphql": ("graphql", "graph ql"),
    "rest": ("rest api", "restful", "rest apis"),
    "grpc": ("grpc", "g rpc"),
    "devops": ("devops", "dev ops"),
    "ci/cd": ("ci/cd", "cicd", "ci-cd", "continuous integration"),
    "linux": ("linux", "ubuntu", "debian"),
    "git": ("git",),
    "agile": ("agile",),
    "scrum": ("scrum",),
    "figma": ("figma",),
    "unity": ("unity3d", "unity"),
    "solidity": ("solidity",),
    "blockchain": ("blockchain", "web3", "web 3"),
    "html": ("html5", "html"),
    "css": ("css3", "css"),
    "bash": ("bash", "shell scripting"),
    "playwright": ("playwright",),
    "selenium": ("selenium",),
    "jenkins": ("jenkins",),
    "github actions": ("github actions", "github-actions"),
    "prometheus": ("prometheus",),
    "grafana": ("grafana",),
    "snowflake": ("snowflake",),
    "dbt": ("dbt",),
    "mlops": ("mlops", "ml ops"),
}

# Stable display order (canonical names). Length is the public taxonomy size.
SKILLS: list[str] = list(SKILL_ALIASES.keys())

# First matching pattern wins. More specific / compound roles come first.
ROLE_PATTERNS: list[tuple[str, str]] = [
    (
        r"\b(machine learning|ml engineer|mlops|ml ops|deep learning|"
        r"ai engineer|ai researcher|llm engineer|nlp engineer|"
        r"computer vision|data scientist|genai|generative ai|"
        r"ai native|ai agent)\b",
        "ml/ai",
    ),
    (
        r"\b(data engineer|analytics engineer|data analyst|bi engineer|"
        r"etl engineer|warehouse|datenanalyst|dateningenieur)\b",
        "data",
    ),
    (
        r"\b(devops|sre|site reliability|platform engineer|"
        r"infrastructure engineer|cloud engineer|platform ops|"
        r"system engineer|systems engineer|netzwerk|firewall|"
        r"virtualisierung|site reliability)\b",
        "devops",
    ),
    (
        r"\b(android|ios|mobile engineer|mobile developer|flutter|"
        r"react native|swift engineer|kotlin android|mobile)\b",
        "mobile",
    ),
    (
        r"\b(full[\s-]?stack|fullstack)\b",
        "fullstack",
    ),
    (
        r"\b(front[\s-]?end|frontend|ui engineer|react developer|"
        r"vue developer|angular developer|frontend-entwickler)\b",
        "frontend",
    ),
    (
        r"\b(back[\s-]?end|backend|api engineer|server[\s-]?side|"
        r"golang engineer|java engineer|python engineer|"
        r"backend-entwickler|rust engineer)\b",
        "backend",
    ),
    (
        r"\b(qa engineer|sdet|test engineer|quality assurance|"
        r"automation tester|qa analyst|software development engineer in test|"
        r"quality engineer)\b",
        "qa",
    ),
    (
        r"\b(product manager|product owner|product analyst|"
        r"technical product|produktmanager)\b",
        "product",
    ),
    (
        r"\b(product designer|ux designer|ui designer|ui/ux|"
        r"graphic designer|visual designer|produktdesigner)\b",
        "design",
    ),
]

# Used when the title is a generic engineer/developer line.
GENERIC_TECH_TITLE = (
    r"\b(software engineer|software developer|softwareentwicklung|"
    r"entwickler|desarrollador|desenvolvedor|programmer|ingenieur|"
    r"ingeniero|swe\b|staff engineer|principal engineer|"
    r"engineering manager)\b"
)

# Soft / ubiquitous words that must not, by themselves, mark a job as tech.
SOFT_SKILLS: frozenset[str] = frozenset({"agile", "scrum", "git"})

# Skill → role votes used when the title is generic.
SKILL_ROLE_HINTS: dict[str, str] = {
    "pytorch": "ml/ai",
    "tensorflow": "ml/ai",
    "llm": "ml/ai",
    "rag": "ml/ai",
    "langchain": "ml/ai",
    "mlops": "ml/ai",
    "scikit-learn": "ml/ai",
    "prompt engineering": "ml/ai",
    "openai": "ml/ai",
    "huggingface": "ml/ai",
    "spark": "data",
    "airflow": "data",
    "dbt": "data",
    "snowflake": "data",
    "pandas": "data",
    "numpy": "data",
    "flutter": "mobile",
    "dart": "mobile",
    "swift": "mobile",
    "kotlin": "mobile",
    "react native": "mobile",
    "kubernetes": "devops",
    "terraform": "devops",
    "ansible": "devops",
    "helm": "devops",
    "prometheus": "devops",
    "grafana": "devops",
    "devops": "devops",
    "jenkins": "devops",
    "react": "frontend",
    "vue": "frontend",
    "angular": "frontend",
    "svelte": "frontend",
    "next.js": "frontend",
    "html": "frontend",
    "css": "frontend",
    "playwright": "qa",
    "selenium": "qa",
    "figma": "design",
    "django": "backend",
    "flask": "backend",
    "fastapi": "backend",
    "node": "backend",
    "express": "backend",
    "nestjs": "backend",
    "go": "backend",
    "java": "backend",
    "rust": "backend",
    "php": "backend",
    "ruby": "backend",
    "c#": "backend",
    ".net": "backend",
    "postgres": "backend",
    "grpc": "backend",
    "kafka": "backend",
    "c++": "backend",
}

# Location fragments → canonical country / region label.
LOCATION_ALIASES: dict[str, str] = {
    "usa": "United States",
    "us": "United States",
    "u.s.": "United States",
    "u.s.a.": "United States",
    "u.s.a": "United States",
    "united states": "United States",
    "united states of america": "United States",
    "america": "United States",
    "uk": "United Kingdom",
    "u.k.": "United Kingdom",
    "u.k": "United Kingdom",
    "england": "United Kingdom",
    "scotland": "United Kingdom",
    "wales": "United Kingdom",
    "great britain": "United Kingdom",
    "united kingdom": "United Kingdom",
    "britain": "United Kingdom",
    "deutschland": "Germany",
    "germany": "Germany",
    "niederlande": "Netherlands",
    "the netherlands": "Netherlands",
    "netherlands": "Netherlands",
    "holland": "Netherlands",
    "france": "France",
    "spain": "Spain",
    "españa": "Spain",
    "portugal": "Portugal",
    "italy": "Italy",
    "italia": "Italy",
    "poland": "Poland",
    "polska": "Poland",
    "canada": "Canada",
    "brazil": "Brazil",
    "brasil": "Brazil",
    "argentina": "Argentina",
    "mexico": "Mexico",
    "méxico": "Mexico",
    "india": "India",
    "singapore": "Singapore",
    "australia": "Australia",
    "ireland": "Ireland",
    "sweden": "Sweden",
    "norway": "Norway",
    "denmark": "Denmark",
    "finland": "Finland",
    "switzerland": "Switzerland",
    "austria": "Austria",
    "belgium": "Belgium",
    "czechia": "Czechia",
    "czech republic": "Czechia",
    "israel": "Israel",
    "japan": "Japan",
    "south korea": "South Korea",
    "korea": "South Korea",
    "chile": "Chile",
    "colombia": "Colombia",
    "uruguay": "Uruguay",
    "romania": "Romania",
    "hungary": "Hungary",
    "ukraine": "Ukraine",
    "estonia": "Estonia",
    "lithuania": "Lithuania",
    "latvia": "Latvia",
    "greece": "Greece",
    "turkey": "Turkey",
    "uae": "United Arab Emirates",
    "united arab emirates": "United Arab Emirates",
    "south africa": "South Africa",
    "new zealand": "New Zealand",
    "philippines": "Philippines",
    "indonesia": "Indonesia",
    "vietnam": "Vietnam",
    "thailand": "Thailand",
    "malaysia": "Malaysia",
    "taiwan": "Taiwan",
    "hong kong": "Hong Kong",
    "europe": "Europe",
    "eu": "Europe",
    "emea": "EMEA",
    "latam": "LATAM",
    "apac": "APAC",
    "apac region": "APAC",
    "remote": "Remote",
    "remoto": "Remote",
    "worldwide": "Remote",
    "anywhere": "Remote",
    "global": "Remote",
    "work from home": "Remote",
    "wfh": "Remote",
    "distributed": "Remote",
    "hybrid": "Hybrid",
    "nordrhein-westfalen": "Germany",
    "westfalen": "Germany",
    "bayern": "Germany",
    "baden-württemberg": "Germany",
    "baden-wurttemberg": "Germany",
    "hauts-de-france": "France",
    "île-de-france": "France",
    "ile-de-france": "France",
}

CITY_TO_COUNTRY: dict[str, str] = {
    "berlin": "Germany",
    "munich": "Germany",
    "münchen": "Germany",
    "hamburg": "Germany",
    "frankfurt": "Germany",
    "cologne": "Germany",
    "köln": "Germany",
    "stuttgart": "Germany",
    "leipzig": "Germany",
    "düsseldorf": "Germany",
    "dusseldorf": "Germany",
    "essen": "Germany",
    "coburg": "Germany",
    "freiburg": "Germany",
    "freiburg im breisgau": "Germany",
    "osnabrück": "Germany",
    "osnabruck": "Germany",
    "regensburg": "Germany",
    "wiesbaden": "Germany",
    "dortmund": "Germany",
    "nuremberg": "Germany",
    "nürnberg": "Germany",
    "compiègne": "France",
    "compiegne": "France",
    "redwood city": "United States",
    "cincinnati": "United States",
    "mississauga": "Canada",
    "bristol": "United Kingdom",
    "agra": "India",
    "dubai": "United Arab Emirates",
    "abu dhabi": "United Arab Emirates",
    "amsterdam": "Netherlands",
    "rotterdam": "Netherlands",
    "utrecht": "Netherlands",
    "london": "United Kingdom",
    "manchester": "United Kingdom",
    "edinburgh": "United Kingdom",
    "paris": "France",
    "lyon": "France",
    "madrid": "Spain",
    "barcelona": "Spain",
    "valencia": "Spain",
    "lisbon": "Portugal",
    "lisboa": "Portugal",
    "porto": "Portugal",
    "warsaw": "Poland",
    "warszawa": "Poland",
    "krakow": "Poland",
    "kraków": "Poland",
    "wroclaw": "Poland",
    "new york": "United States",
    "nyc": "United States",
    "brooklyn": "United States",
    "san francisco": "United States",
    "sf": "United States",
    "bay area": "United States",
    "los angeles": "United States",
    "seattle": "United States",
    "austin": "United States",
    "boston": "United States",
    "chicago": "United States",
    "denver": "United States",
    "miami": "United States",
    "atlanta": "United States",
    "toronto": "Canada",
    "vancouver": "Canada",
    "montreal": "Canada",
    "montréal": "Canada",
    "sao paulo": "Brazil",
    "são paulo": "Brazil",
    "rio de janeiro": "Brazil",
    "buenos aires": "Argentina",
    "mexico city": "Mexico",
    "ciudad de mexico": "Mexico",
    "bangalore": "India",
    "bengaluru": "India",
    "hyderabad": "India",
    "pune": "India",
    "mumbai": "India",
    "delhi": "India",
    "gurgaon": "India",
    "gurugram": "India",
    "singapore": "Singapore",
    "sydney": "Australia",
    "melbourne": "Australia",
    "dublin": "Ireland",
    "stockholm": "Sweden",
    "oslo": "Norway",
    "copenhagen": "Denmark",
    "helsinki": "Finland",
    "zurich": "Switzerland",
    "zürich": "Switzerland",
    "geneva": "Switzerland",
    "vienna": "Austria",
    "wien": "Austria",
    "prague": "Czechia",
    "praha": "Czechia",
    "tel aviv": "Israel",
    "tokyo": "Japan",
    "seoul": "South Korea",
    "santiago": "Chile",
    "bogota": "Colombia",
    "bogotá": "Colombia",
    "bucharest": "Romania",
    "budapest": "Hungary",
    "kyiv": "Ukraine",
    "tallinn": "Estonia",
    "vilnius": "Lithuania",
    "riga": "Latvia",
    "athens": "Greece",
    "istanbul": "Turkey",
    "dubai": "United Arab Emirates",
    "cape town": "South Africa",
    "auckland": "New Zealand",
    "manila": "Philippines",
    "jakarta": "Indonesia",
    "ho chi minh": "Vietnam",
    "bangkok": "Thailand",
    "kuala lumpur": "Malaysia",
    "taipei": "Taiwan",
}

COUNTRY_FLAGS: dict[str, str] = {
    "United States": "US",
    "United Kingdom": "UK",
    "Germany": "DE",
    "Netherlands": "NL",
    "France": "FR",
    "Spain": "ES",
    "Portugal": "PT",
    "Italy": "IT",
    "Poland": "PL",
    "Canada": "CA",
    "Brazil": "BR",
    "Argentina": "AR",
    "Mexico": "MX",
    "India": "IN",
    "Singapore": "SG",
    "Australia": "AU",
    "Ireland": "IE",
    "Sweden": "SE",
    "Norway": "NO",
    "Denmark": "DK",
    "Finland": "FI",
    "Switzerland": "CH",
    "Austria": "AT",
    "Belgium": "BE",
    "Czechia": "CZ",
    "Israel": "IL",
    "Japan": "JP",
    "South Korea": "KR",
    "Chile": "CL",
    "Colombia": "CO",
    "Uruguay": "UY",
    "Romania": "RO",
    "Hungary": "HU",
    "Ukraine": "UA",
    "Estonia": "EE",
    "Lithuania": "LT",
    "Latvia": "LV",
    "Greece": "GR",
    "Turkey": "TR",
    "United Arab Emirates": "AE",
    "South Africa": "ZA",
    "New Zealand": "NZ",
    "Philippines": "PH",
    "Indonesia": "ID",
    "Vietnam": "VN",
    "Thailand": "TH",
    "Malaysia": "MY",
    "Taiwan": "TW",
    "Hong Kong": "HK",
    "Remote": "ANY",
    "Europe": "EU",
    "EMEA": "EM",
    "LATAM": "LA",
    "APAC": "AP",
}
